# Generated by Django 4.1.7 on 2023-03-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_post_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Mental Health', 'Mental Health'), ('Heart Diseases', 'Heart Diseases'), ('Covid19', 'Covid19'), ('Immunization', 'Immunization')], max_length=50),
        ),
    ]
