# Generated by Django 4.1.7 on 2023-03-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_appointment_takeappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=None, error_messages={'required': 'Role must be provided'}, max_length=12),
        ),
    ]
