# Generated by Django 4.1.7 on 2023-03-17 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsRequiredDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(default='', max_length=100)),
                ('date_of_appointment', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default='00:00:00')),
            ],
        ),
    ]
