# Generated by Django 4.1.7 on 2023-03-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsrequireddetails',
            name='doctor_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
